# imports


def SimpleCSVParse(fileloc):
    """
    Simple CSV handler for AOC 2k19, handles CSV list similar to those generated by https://adventofcode.com/2019/day/1/input
    :param fileloc: csv file to be handled
    :return: list of items in CSV
    """
    import csv

    data = []

    with open(fileloc) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            data.append(int(row[0]))

    return data

def FuelReq(mass):
    mass = mass/3
    mass = int(mass)
    mass = mass - 2

    return mass


if __name__ == '__main__':

    address = 'day1_data.csv'
    data = SimpleCSVParse(address)

    ## PART 1
    # check test data
    test_data = [12, 14, 1969, 100756]
    test_results = []
    for mass in test_data:
        test_results.append(FuelReq(mass))

    # check real data
    results = []
    for mass in data:
        results.append(FuelReq(mass))

    massSum = sum(results)
    print('Part 1 Result = ',massSum)

    ## PART 2
    test_data [14, ]



